// Aanvullende inhoud voor het nieuwe ontwerp (procesflow, werkgebied, FAQ, volledige werkenlijst).
// Feiten komen uit elektromax-info.txt en de offerte-tekst van de vorige site.

const towns = [
  "Antwerpen",
  "Berchem",
  "Borgerhout",
  "Deurne",
  "Merksem",
  "Ekeren",
  "Wilrijk",
  "Hoboken",
  "Mortsel",
  "Edegem",
  "Kontich",
  "Schoten",
  "Brasschaat",
  "Kapellen",
  "Zwijndrecht",
  "Wommelgem",
];

export const extras = {
  nl: {
    heroBadge: "35 jaar ervaring · Regio Antwerpen",
    heroTitle: ["Uw elektricien", "in Antwerpen."],
    heroAccent: "Veilig. Netjes. AREI-conform.",
    heroChecks: ["Gratis offerte", "Klaar voor de keuring", "Woning, handel & werf"],
    callNow: "Bel nu",
    freeQuote: "Gratis offerte",
    whatsapp: "WhatsApp",
    floatingOk: "Keuring in orde",
    floatingOkSub: "Installatie conform AREI",
    floatingYears: "jaar vakmanschap",
    stats: [
      { value: 35, suffix: "+", label: "Jaar ervaring" },
      { value: 200, suffix: "+", label: "Projecten" },
      { value: 18, suffix: "", label: "Specialisaties" },
      { value: 25, suffix: " jaar", label: "Geldig keuringsattest (woning)" },
    ],
    servicesKicker: "Wat we doen",
    allWorksKicker: "Volledig aanbod",
    allWorksTitle: "Voor volgende werken mag u ons contacteren",
    allWorksLead:
      "Elektriciteit is meer dan een zekering en een stopcontact. Installaties staan steeds meer in connectie met elkaar: van domotica tot zonnepanelen, batterij en laadpaal.",
    works: [
      { icon: "Cable", label: "Volledige elektrische installatie plaatsen" },
      { icon: "Cpu", label: "Domotica" },
      { icon: "Gauge", label: "Zekeringkast vernieuwen / aanpassen" },
      { icon: "ToggleRight", label: "Stopcontacten en schakelaars vervangen" },
      { icon: "Lightbulb", label: "Extra stopcontacten of lichtpunten" },
      { icon: "ShieldCheck", label: "Installatie voorbereiden voor de keuring" },
      { icon: "FileText", label: "Eendraadsschema en situatieschema" },
      { icon: "Sun", label: "Zonnepanelen plaatsen" },
      { icon: "PlugZap", label: "Laadpalen / wallbox" },
      { icon: "BatteryCharging", label: "Thuisbatterij plaatsen" },
      { icon: "Cctv", label: "Camera-installatie" },
      { icon: "Video", label: "Parlofonie & videofonie (Bticino)" },
      { icon: "Flame", label: "Brandinstallatie" },
      { icon: "AlarmSmoke", label: "Rookmelders installeren" },
      { icon: "Zap", label: "Krachtstroom 400V" },
      { icon: "ArrowDownToLine", label: "Aarding aanleggen" },
      { icon: "Siren", label: "Storingen & kortsluiting herstellen" },
      { icon: "Factory", label: "Industriële projecten" },
    ],
    keuring: {
      kicker: "Elektrische keuring",
      title: "Afgekeurd? Wij brengen uw installatie in orde.",
      lead:
        "We controleren uw installatie, lossen de opmerkingen van het keuringsorganisme op en zorgen dat alles klaar is voor een geldig keuringsattest.",
      facts: [
        { value: "25 jaar", label: "geldig attest voor een woning" },
        { value: "5 jaar", label: "geldig attest voor een handelszaak" },
      ],
      points: [
        "In orde brengen van afgekeurde installaties",
        "Tekenen van situatie- en eendraadsschema's",
        "Zekeringkast vernieuwen en aarding aanleggen",
        "Nieuwbouw en renovatie",
      ],
      cta: "Plan een controle",
    },
    processKicker: "Zo werken we",
    processTitle: "Van eerste contact tot oplevering",
    process: [
      { title: "Contact", text: "Bel, mail of stuur een WhatsApp met foto's van uw situatie." },
      { title: "Plaatsbezoek", text: "We bekijken de installatie ter plaatse en maken een gratis offerte." },
      { title: "Uitvoering", text: "Nette, veilige uitvoering volgens AREI en volgens planning." },
      { title: "Oplevering", text: "Ordelijke kast, schema's en een installatie klaar voor de keuring." },
    ],
    projectsKicker: "Realisaties",
    areaKicker: "Werkgebied",
    areaTitle: "Antwerpen en omgeving",
    areaLead:
      "We werken lokaal in Antwerpen en de omliggende gemeenten. Voor grotere projecten zijn we actief in heel België en de buurlanden.",
    towns,
    areaMore: "en omliggende gemeenten",
    faqKicker: "Veelgestelde vragen",
    faqTitle: "Goed om te weten",
    faq: [
      {
        q: "Mijn installatie werd afgekeurd. Wat nu?",
        a: "Geen paniek. We bekijken het keuringsverslag, voeren de nodige aanpassingen uit en zetten alles klaar voor de herkeuring. Die moet gebeuren binnen de termijn die op het verslag staat (meestal 12 maanden).",
      },
      {
        q: "Hoe lang is een keuringsattest geldig?",
        a: "Voor een woning is een conform keuringsattest 25 jaar geldig. Voor een handelszaak of niet-residentieel gebouw is dat 5 jaar.",
      },
      {
        q: "Is de offerte gratis?",
        a: "Ja. Na een kort gesprek of plaatsbezoek krijgt u een gratis en vrijblijvende offerte.",
      },
      {
        q: "Maken jullie ook het eendraadsschema en situatieschema?",
        a: "Ja. We tekenen de situatie- en eendraadsschema's die nodig zijn voor de keuring en voor uw eigen dossier.",
      },
      {
        q: "Kunnen jullie een laadpaal of thuisbatterij plaatsen?",
        a: "Ja. We controleren eerst de beschikbare capaciteit en beveiligingen en plaatsen daarna de laadpaal, wallbox of batterij veilig en netjes.",
      },
      {
        q: "In welke regio zijn jullie actief?",
        a: "Vooral in Antwerpen en omgeving. Voor grotere en industriële projecten werken we in heel België en de buurlanden.",
      },
    ],
    ctaTitle: "Klaar om te starten?",
    ctaLead: "Vraag vandaag nog uw gratis offerte aan. We denken praktisch mee en communiceren duidelijk.",
    offer: {
      badge: "GRATIS offerte",
      title: "Interesse?",
      lines: [
        "Regio Antwerpen · 35 jaar ervaring",
        "In orde brengen van afgekeurde installaties",
        "Keuringsattest woning: 25 jaar geldig · handelszaak: 5 jaar",
        "Situatie- en eendraadsschema's tekenen",
        "Parlofonie & videofonie Bticino",
        "Zekeringkast vernieuwen · aarding aanleggen",
        "Nieuwbouw en renovatie",
        "Storing of kortsluiting in orde maken",
        "Laadpalen & wallbox · industriële projecten",
      ],
      email: "E-mail",
      dismiss: "Niet geïnteresseerd",
      waMessage: "Hallo, ik wil graag een gratis offerte.",
    },
    waMessage: "Hallo, ik neem contact op via de website van Elektromax.",
    mobileCall: "Bellen",
    otherServices: "Andere diensten",
    sendWhatsapp: "Verstuur via WhatsApp",
    formNote: "Uw bericht wordt geopend in uw e-mail- of WhatsApp-app. Er wordt niets opgeslagen op deze website.",
    mapTitle: "Werkgebied Elektromax: Antwerpen",
    aboutKicker: "Over Elektromax",
    contactKicker: "Contact",
    projectsLeadKicker: "Typische opdrachten",
  },

  en: {
    heroBadge: "35 years of experience · Antwerp Region",
    heroTitle: ["Your electrician", "in Antwerp."],
    heroAccent: "Safe. Tidy. AREI-compliant.",
    heroChecks: ["Free quote", "Ready for inspection", "Homes, shops & sites"],
    callNow: "Call now",
    freeQuote: "Free quote",
    whatsapp: "WhatsApp",
    floatingOk: "Inspection passed",
    floatingOkSub: "AREI-compliant installation",
    floatingYears: "years of craftsmanship",
    stats: [
      { value: 35, suffix: "+", label: "Years of experience" },
      { value: 200, suffix: "+", label: "Projects" },
      { value: 18, suffix: "", label: "Specialisations" },
      { value: 25, suffix: " yrs", label: "Valid inspection certificate (home)" },
    ],
    servicesKicker: "What we do",
    allWorksKicker: "Full range",
    allWorksTitle: "You can contact us for the following works",
    allWorksLead:
      "Electricity is more than a fuse and a socket. Installations are increasingly connected: from home automation to solar panels, batteries and EV chargers.",
    works: [
      { icon: "Cable", label: "Complete electrical installation" },
      { icon: "Cpu", label: "Home automation (domotics)" },
      { icon: "Gauge", label: "Renew / adapt distribution board" },
      { icon: "ToggleRight", label: "Replace sockets and switches" },
      { icon: "Lightbulb", label: "Extra sockets or light points" },
      { icon: "ShieldCheck", label: "Prepare installation for inspection" },
      { icon: "FileText", label: "Single-line and layout diagrams" },
      { icon: "Sun", label: "Solar panel installation" },
      { icon: "PlugZap", label: "EV chargers / wallbox" },
      { icon: "BatteryCharging", label: "Home battery installation" },
      { icon: "Cctv", label: "Camera installation" },
      { icon: "Video", label: "Intercom & video intercom (Bticino)" },
      { icon: "Flame", label: "Fire installation" },
      { icon: "AlarmSmoke", label: "Smoke detector installation" },
      { icon: "Zap", label: "Three-phase power 400V" },
      { icon: "ArrowDownToLine", label: "Earthing installation" },
      { icon: "Siren", label: "Faults & short-circuit repair" },
      { icon: "Factory", label: "Industrial projects" },
    ],
    keuring: {
      kicker: "Electrical inspection",
      title: "Failed inspection? We'll bring your installation up to standard.",
      lead:
        "We check your installation, fix the remarks from the inspection body and make sure everything is ready for a valid inspection certificate.",
      facts: [
        { value: "25 years", label: "certificate validity for a home" },
        { value: "5 years", label: "certificate validity for a shop" },
      ],
      points: [
        "Fixing rejected installations",
        "Drawing layout and single-line diagrams",
        "Renewing distribution boards and earthing",
        "New construction and renovation",
      ],
      cta: "Book a check",
    },
    processKicker: "How we work",
    processTitle: "From first contact to handover",
    process: [
      { title: "Contact", text: "Call, email or send a WhatsApp with photos of your situation." },
      { title: "Site visit", text: "We inspect the installation on site and prepare a free quote." },
      { title: "Execution", text: "Tidy, safe work according to AREI and according to plan." },
      { title: "Handover", text: "Organised board, diagrams and an installation ready for inspection." },
    ],
    projectsKicker: "Our work",
    areaKicker: "Service area",
    areaTitle: "Antwerp and surroundings",
    areaLead:
      "We work locally in Antwerp and the surrounding municipalities. For larger projects we are active throughout Belgium and neighbouring countries.",
    towns,
    areaMore: "and surrounding municipalities",
    faqKicker: "FAQ",
    faqTitle: "Good to know",
    faq: [
      {
        q: "My installation failed the inspection. What now?",
        a: "Don't worry. We review the inspection report, carry out the required changes and prepare everything for the re-inspection, which must take place within the deadline on the report (usually 12 months).",
      },
      {
        q: "How long is an inspection certificate valid?",
        a: "For a home, a compliant certificate is valid for 25 years. For a shop or non-residential building it is 5 years.",
      },
      {
        q: "Is the quote free?",
        a: "Yes. After a short call or site visit you receive a free, no-obligation quote.",
      },
      {
        q: "Do you also draw the single-line and layout diagrams?",
        a: "Yes. We draw the layout and single-line diagrams needed for the inspection and for your own records.",
      },
      {
        q: "Can you install an EV charger or home battery?",
        a: "Yes. We first check the available capacity and protections, then install the charger, wallbox or battery safely and neatly.",
      },
      {
        q: "Which area do you cover?",
        a: "Mainly Antwerp and surroundings. For larger and industrial projects we work throughout Belgium and neighbouring countries.",
      },
    ],
    ctaTitle: "Ready to get started?",
    ctaLead: "Request your free quote today. We think along practically and communicate clearly.",
    offer: {
      badge: "Free quote",
      title: "Interested?",
      lines: [
        "Antwerp Region · 35 years of experience",
        "Fixing rejected installations",
        "Inspection certificate home: valid 25 years · shop: 5 years",
        "Layout and single-line diagrams",
        "Bticino intercom & video intercom",
        "Renewing distribution boards · earthing",
        "New construction and renovation",
        "Fault or short-circuit repair",
        "EV chargers & wallbox · industrial projects",
      ],
      email: "Email",
      dismiss: "Not interested",
      waMessage: "Hello, I would like a free quote.",
    },
    waMessage: "Hello, I am contacting you via the Elektromax website.",
    mobileCall: "Call",
    otherServices: "Other services",
    sendWhatsapp: "Send via WhatsApp",
    formNote: "Your message opens in your email or WhatsApp app. Nothing is stored on this website.",
    mapTitle: "Elektromax service area: Antwerp",
    aboutKicker: "About Elektromax",
    contactKicker: "Contact",
    projectsLeadKicker: "Typical jobs",
  },

  tr: {
    heroBadge: "35 yıllık tecrübe · Antwerpen bölgesi",
    heroTitle: ["Antwerpen'deki", "elektrikçiniz."],
    heroAccent: "Güvenli. Temiz. AREI uyumlu.",
    heroChecks: ["Ücretsiz teklif", "Keuring'e hazır", "Ev, işyeri ve şantiye"],
    callNow: "Hemen ara",
    freeQuote: "Ücretsiz teklif",
    whatsapp: "WhatsApp",
    floatingOk: "Keuring tamam",
    floatingOkSub: "AREI uyumlu tesisat",
    floatingYears: "yıllık ustalık",
    stats: [
      { value: 35, suffix: "+", label: "Yıl tecrübe" },
      { value: 200, suffix: "+", label: "Proje" },
      { value: 18, suffix: "", label: "Uzmanlık alanı" },
      { value: 25, suffix: " yıl", label: "Geçerli keuring belgesi (konut)" },
    ],
    servicesKicker: "Neler yapıyoruz",
    allWorksKicker: "Tüm hizmetler",
    allWorksTitle: "Aşağıdaki işler için bize ulaşabilirsiniz",
    allWorksLead:
      "Elektrik, bir sigorta ve prizden ibaret değil. Tesisatlar giderek birbirine bağlanıyor: akıllı evden güneş paneline, bataryadan şarj istasyonuna.",
    works: [
      { icon: "Cable", label: "Komple elektrik tesisatı" },
      { icon: "Cpu", label: "Akıllı ev (domotica)" },
      { icon: "Gauge", label: "Sigorta panosu yenileme / düzenleme" },
      { icon: "ToggleRight", label: "Priz ve anahtar değişimi" },
      { icon: "Lightbulb", label: "Ek priz veya aydınlatma noktası" },
      { icon: "ShieldCheck", label: "Tesisatı keuring'e hazırlama" },
      { icon: "FileText", label: "Tek hat ve vaziyet şeması" },
      { icon: "Sun", label: "Güneş paneli montajı" },
      { icon: "PlugZap", label: "Şarj istasyonu / wallbox" },
      { icon: "BatteryCharging", label: "Ev bataryası montajı" },
      { icon: "Cctv", label: "Kamera kurulumu" },
      { icon: "Video", label: "Diyafon ve görüntülü diyafon (Bticino)" },
      { icon: "Flame", label: "Yangın tesisatı" },
      { icon: "AlarmSmoke", label: "Duman dedektörü montajı" },
      { icon: "Zap", label: "Trifaze 400V tesisat" },
      { icon: "ArrowDownToLine", label: "Topraklama" },
      { icon: "Siren", label: "Arıza ve kısa devre onarımı" },
      { icon: "Factory", label: "Endüstriyel projeler" },
    ],
    keuring: {
      kicker: "Elektrik keuring'i",
      title: "Keuring'den geçemediniz mi? Tesisatınızı biz düzeltelim.",
      lead:
        "Tesisatınızı kontrol ediyor, keuring kurumunun tespit ettiği eksikleri gideriyor ve geçerli bir keuring belgesi için her şeyi hazırlıyoruz.",
      facts: [
        { value: "25 yıl", label: "konut için belge geçerliliği" },
        { value: "5 yıl", label: "işyeri için belge geçerliliği" },
      ],
      points: [
        "Reddedilen tesisatların düzeltilmesi",
        "Vaziyet ve tek hat şemalarının çizilmesi",
        "Pano yenileme ve topraklama",
        "Yeni bina ve renovasyon",
      ],
      cta: "Kontrol randevusu al",
    },
    processKicker: "Nasıl çalışıyoruz",
    processTitle: "İlk temastan teslime kadar",
    process: [
      { title: "İletişim", text: "Arayın, mail atın veya durumunuzun fotoğraflarını WhatsApp'tan gönderin." },
      { title: "Yerinde inceleme", text: "Tesisatı yerinde inceler, ücretsiz teklif hazırlarız." },
      { title: "Uygulama", text: "AREI'ye uygun, temiz ve planlı işçilik." },
      { title: "Teslim", text: "Düzenli pano, şemalar ve keuring'e hazır tesisat." },
    ],
    projectsKicker: "Çalışmalarımız",
    areaKicker: "Hizmet bölgesi",
    areaTitle: "Antwerpen ve çevresi",
    areaLead:
      "Antwerpen ve çevre belediyelerde yerel olarak çalışıyoruz. Büyük projeler için tüm Belçika'da ve komşu ülkelerde aktifiz.",
    towns,
    areaMore: "ve çevre belediyeler",
    faqKicker: "Sık sorulan sorular",
    faqTitle: "Bilmeniz gerekenler",
    faq: [
      {
        q: "Tesisatım keuring'den geçemedi. Ne yapmalıyım?",
        a: "Endişelenmeyin. Keuring raporunu inceler, gerekli düzeltmeleri yapar ve tekrar keuring için her şeyi hazırlarız. Tekrar keuring, raporda belirtilen süre içinde (genellikle 12 ay) yapılmalıdır.",
      },
      {
        q: "Keuring belgesi ne kadar geçerli?",
        a: "Konutlarda uygun bir keuring belgesi 25 yıl geçerlidir. İşyeri veya konut dışı binalarda bu süre 5 yıldır.",
      },
      {
        q: "Teklif ücretsiz mi?",
        a: "Evet. Kısa bir görüşme veya yerinde incelemeden sonra ücretsiz ve bağlayıcı olmayan bir teklif alırsınız.",
      },
      {
        q: "Tek hat ve vaziyet şemasını da çiziyor musunuz?",
        a: "Evet. Keuring ve kendi dosyanız için gerekli vaziyet ve tek hat şemalarını çiziyoruz.",
      },
      {
        q: "Şarj istasyonu veya ev bataryası kurabilir misiniz?",
        a: "Evet. Önce mevcut kapasiteyi ve korumaları kontrol eder, ardından şarj istasyonunu, wallbox'ı veya bataryayı güvenli ve temiz şekilde kurarız.",
      },
      {
        q: "Hangi bölgede hizmet veriyorsunuz?",
        a: "Ağırlıklı olarak Antwerpen ve çevresinde. Büyük ve endüstriyel projeler için tüm Belçika'da ve komşu ülkelerde çalışıyoruz.",
      },
    ],
    ctaTitle: "Başlamaya hazır mısınız?",
    ctaLead: "Ücretsiz teklifinizi bugün isteyin. Pratik çözümler üretir, açık iletişim kurarız.",
    offer: {
      badge: "Ücretsiz teklif",
      title: "İlgileniyor musunuz?",
      lines: [
        "Antwerpen bölgesi · 35 yıllık tecrübe",
        "Reddedilen tesisatların düzeltilmesi",
        "Keuring belgesi konut: 25 yıl · işyeri: 5 yıl geçerli",
        "Vaziyet ve tek hat şemaları",
        "Bticino diyafon ve görüntülü diyafon",
        "Pano yenileme · topraklama",
        "Yeni bina ve renovasyon",
        "Arıza veya kısa devre onarımı",
        "Şarj istasyonu & wallbox · endüstriyel projeler",
      ],
      email: "E-posta",
      dismiss: "İlgilenmiyorum",
      waMessage: "Merhaba, ücretsiz teklif almak istiyorum.",
    },
    waMessage: "Merhaba, Elektromax web sitesi üzerinden ulaşıyorum.",
    mobileCall: "Ara",
    otherServices: "Diğer hizmetler",
    sendWhatsapp: "WhatsApp ile gönder",
    formNote: "Mesajınız e-posta veya WhatsApp uygulamanızda açılır. Bu sitede hiçbir veri saklanmaz.",
    mapTitle: "Elektromax hizmet bölgesi: Antwerpen",
    aboutKicker: "Elektromax hakkında",
    contactKicker: "İletişim",
    projectsLeadKicker: "Örnek işler",
  },
};
